#!/usr/bin/env python3
from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parents[1]
SKILLS_DIR = ROOT / "skills"
PROTOCOL_PATH = ROOT / "scripts/chatgpt_skill_resolution_protocol.md"
OUTPUT_PATH = ROOT / "CHATGPT.md"


@dataclass(frozen=True)
class Skill:
    name: str
    description: str
    path: str


def read_frontmatter(path: Path) -> dict[str, object]:
    content = path.read_text(encoding="utf-8")
    match = re.match(r"\A---\s*\n(.*?)\n---(?:\s*\n|\Z)", content, re.DOTALL)
    if not match:
        raise ValueError(f"missing YAML frontmatter: {path.relative_to(ROOT)}")
    fields = yaml.safe_load(match.group(1))
    if not isinstance(fields, dict):
        raise ValueError(f"frontmatter must be a mapping: {path.relative_to(ROOT)}")
    return fields


def load_skills() -> list[Skill]:
    skill_files = sorted(SKILLS_DIR.glob("*/SKILL.md"), key=lambda path: path.parent.name.casefold())

    skills = []
    for path in skill_files:
        fields = read_frontmatter(path)
        name = fields.get("name")
        description = fields.get("description")
        if not isinstance(name, str) or not name.strip():
            raise ValueError(f"missing skill name: {path.relative_to(ROOT)}")
        if name != path.parent.name:
            raise ValueError(
                f"skill name mismatch: directory={path.parent.name} frontmatter={name}"
            )
        if not isinstance(description, str) or not description.strip():
            raise ValueError(f"missing skill description: {path.relative_to(ROOT)}")
        skills.append(
            Skill(
                name=name,
                description=" ".join(description.split()),
                path=path.relative_to(ROOT).as_posix(),
            )
        )
    return sorted(skills, key=lambda skill: (skill.name.casefold(), skill.name))


def render(skills: list[Skill]) -> str:
    protocol = PROTOCOL_PATH.read_text(encoding="utf-8").strip()
    lines = [
        "<!-- Generated by scripts/build_chatgpt_md.py. Do not edit directly. -->",
        "<!-- ChatGPT Web routing only. Codex must ignore this file. -->",
        "",
        protocol,
        "",
        "# Available Skills",
        "",
    ]
    for skill in skills:
        lines.extend(
            (
                f"## {skill.name}",
                "",
                skill.description,
                "",
                f"Entrypoint: `{skill.path}`",
                "",
            )
        )
    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Build the ChatGPT Web skill routing manifest")
    parser.add_argument(
        "--check",
        action="store_true",
        help="return non-zero when CHATGPT.md differs from generated output",
    )
    args = parser.parse_args(argv)
    skills = load_skills()
    expected = render(skills)
    if args.check:
        current = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else None
        if current != expected:
            print("CHATGPT.md is stale; run python3 scripts/build_chatgpt_md.py", file=sys.stderr)
            return 1
        print("CHATGPT.md is current")
        return 0
    OUTPUT_PATH.write_text(expected, encoding="utf-8")
    print(f"wrote {OUTPUT_PATH.relative_to(ROOT)} with {len(skills)} skills")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
